# Example Site settings

# google_analytics: UA-NNNNNNNN-N
remote_theme: awflwafl/jekyll-theme-console

header_pages:
  - index.md
  - templates.md
  - dotfiles.md
  - resources.md

footer: 'follow <a href="https://twitter.com/awflwafl">@awflwafl on twitter</a>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
